### ISSUE TITLE
Alternative .htaccess code

### ISSUE THREAD

**Issue by SamM** [anandkunal/ToroPHP#76]
I'm using Apache version 2.2.24 and for some reason neither of the two snippets of code that you posted to use in my .htaccess were working properly. On another server (Apache 2.2.19) the "FallbackResource /index.php" worked perfectly, but it didn't work well on my server.

Here's the code I found that worked for on my server:

RewriteBase /INSERT/PATH/TO/BASE/DIRECTORY
RewriteEngine on
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond $1 !^(index.php)
RewriteRule .\* index.php/$0 [L]

Without the RewriteBase all I got was a 404 error ".../index.php/ was not found".

**Comment by uc-Pri** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online).

## Job Description:
- **Position:** Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan
  - Company-contributed retirement plan
  - Flexible working hours
  - Collaborative and inclusive work environment

## Requirements:
- Proven experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Familiarity with frameworks such as React, Angular, or Vue.js
- Problem-solving skills and ability to work in a team

**Note:** This position is open to candidates from anywhere in the world.
NourseSavio94, @Babar-Bashir, @Necroraijin, @bobrogden, @formless63, @ZackBradshaw, @disouzaleo, @Bogdanello, @LiorMoshe, @tblakex01, @Richadk, @DanielKrastev-bit, @dengwx11, @kevinsslin, @cja-fin-ds, @Zheng-Chuan, @nsnull0, @dongdong-gogogo, @amitmeel, @RishiSargar
