### ISSUE TITLE
Subdirectory / doesn't work

### ISSUE THREAD

**Issue by Jessestr** [anandkunal/ToroPHP#82]
Toro works on root.
However placed in subdirectory (ravenproj), the root route "/" stops working. The others routes "/journal", "/work" still work. Any ideas?

	RewriteEngine on
	
	RewriteBase /ravenproj
	
	RewriteCond %{REQUEST_FILENAME} !-f
	RewriteCond %{REQUEST_FILENAME} !-d
	
	RewriteCond $1 !^(index.php)
	RewriteRule .* index.php/$0 [L]
	

    Toro::serve(array(
	    "/admin" => "Admin",
	    "/journal" => "Journal",
	    "/about" => "About",
	    "/" => "Work"
    ), '/ravenproj'); // also without the prefix it doesn't work

**Comment by edusis** [comment]
the @VeeeneX solution works for me... after that there is only one issue with the links in _article.php

**Comment by martinbean** [comment]
Please see #34.
