### ISSUE TITLE
how to deal with post requests?

### ISSUE THREAD

**Issue by wdkwdkwdk** [anandkunal/ToroPHP#99]
I know I can use function post() to get the post requests,but what should I set the url?

thanks

**Comment by archistico** [comment]
same question

**Comment by martinbean** [comment]
> but what should I set the url?

Toro’s a router. You can set the URL to whatever you need it to be:

```php
Toro::serve(array(
    '/products' => 'ProductHandler',
));
```
```php
<?php

class ProductHandler {
    function post() {
        // Handle POST request to /products
    }
}
```
